"""Utilities for tracing JAX derivative workloads to jaxpr and analyzing IR features."""

from adscheduler.ir_analysis import (
    FeatureDelta,
    JaxprFeatures,
    analyze_closed_jaxpr,
    compute_feature_delta,
    format_feature_report,
)
from adscheduler.stablehlo_passes import (
    StableHLOPassResult,
    StableHLOPipelineResult,
    StableHLOProgram,
    StableHLOTransformResult,
    available_stablehlo_pass_names,
    default_stablehlo_pass_names,
    format_stablehlo_pipeline_report,
    lower_to_stablehlo,
    lower_workload_to_stablehlo,
    run_stablehlo_pass_pipeline,
    run_stablehlo_transform_pipeline,
    stablehlo_operation_histogram,
)
from adscheduler.workloads import (
    DerivativeWorkload,
    LaplacianBenchmarkConfig,
    PINNBenchmarkConfig,
    TracedDerivativeWorkload,
    available_derivative_workload_names,
    make_derivative_workload,
    normalize_derivative_workload_names,
    trace_derivative_workload,
    trace_derivative_workloads,
)

__all__ = [
    "DerivativeWorkload",
    "FeatureDelta",
    "JaxprFeatures",
    "LaplacianBenchmarkConfig",
    "PINNBenchmarkConfig",
    "StableHLOPassResult",
    "StableHLOPipelineResult",
    "StableHLOProgram",
    "StableHLOTransformResult",
    "TracedDerivativeWorkload",
    "analyze_closed_jaxpr",
    "available_derivative_workload_names",
    "available_stablehlo_pass_names",
    "default_stablehlo_pass_names",
    "compute_feature_delta",
    "format_feature_report",
    "format_stablehlo_pipeline_report",
    "lower_to_stablehlo",
    "lower_workload_to_stablehlo",
    "make_derivative_workload",
    "normalize_derivative_workload_names",
    "run_stablehlo_pass_pipeline",
    "run_stablehlo_transform_pipeline",
    "stablehlo_operation_histogram",
    "trace_derivative_workload",
    "trace_derivative_workloads",
]
